sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t vinaygadiraju/docker-react -f Dockerfile .

script:
  - docker run -e CI=true vinaygadiraju/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-746176912946"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
